"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 03:45:26.895569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('accent_word', sa.String(length=80), nullable=False),
    sa.Column('tagline', sa.String(length=400), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('audience', sa.JSON(), nullable=False),
    sa.Column('outline', sa.JSON(), nullable=False),
    sa.Column('duration_text', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('daily_time', sa.String(length=80), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('map_url', sa.String(length=400), nullable=False),
    sa.Column('fee_text', sa.String(length=120), nullable=False),
    sa.Column('fee_note', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('uq_courses_one_active', ['is_active'], unique=True, sqlite_where=sa.text('is_active = 1'))

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip_hash'), ['ip_hash'], unique=False)

    op.create_table('site_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_key', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=300), nullable=False),
    sa.Column('ip_hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'email_key', name='uq_registration_course_email')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_status'), ['status'], unique=False)

    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('to_email', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_registration_id'), ['registration_id'], unique=False)

    op.create_table('status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=False),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_log_registration_id'), ['registration_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_log_registration_id'))

    op.drop_table('status_log')
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_log_registration_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_created_at'))

    op.drop_table('email_log')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_registrations_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_registrations_created_at'))
        batch_op.drop_index(batch_op.f('ix_registrations_course_id'))

    op.drop_table('registrations')
    op.drop_table('site_settings')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('uq_courses_one_active', sqlite_where=sa.text('is_active = 1'))

    op.drop_table('courses')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
